version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tarefa
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # Monta o diretório com o script de inicialização

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tarefa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
